### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by QingShan-Aspie** [elolab/ILoReg#2]
Hi,

I tried a few times but am still unable to install the package. Here are the error messages:
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo’
Error: Failed to install 'ILoReg' from GitHub:
  (converted from warning) installation of package ‘RcppArmadillo’ had non-zero exit status

Could you help me with this issue? Thank you in advance.

Qingshan

**Comment by j0ntt** [comment]
Hi Qingshan,

Thank you for reporting this issue. It seems to be related to your attempt to install the RcppArmadillo R package on your MacOS.  Did you already try following the instructions at [https://github.com/RcppCore/RcppArmadillo/issues/249](https://github.com/RcppCore/RcppArmadillo/issues/249), which looks very similar to the issue you reported. 

I have myself succesfully installed the package on Windows, Linux and MacOS systems.

I hope this helps.

**Comment by QingshanNeuro** [comment]
Hi,

Thank you for your suggestions! I followed the instructions above and successfully installed it.
